"""The man pages in ``share/man/man1``, generated from the commands' own parsers.

gfal2-util installs a page per ``gfal-*`` command and gfal2 one for
``gfal2_version``; the wheel installs these in their place (``shared-data``
in ``pyproject.toml``). They are written from the parsers, so they cannot
drift from ``--help``: this test fails when they have, and regenerating is::

    python tests/test_cli_man.py
"""

from __future__ import annotations

import argparse
import importlib
import sys
from pathlib import Path

from xgfalclient import cli
from xgfalclient.cli import _base as base

MAN_DIR = Path(__file__).resolve().parent.parent / "share" / "man" / "man1"

HEADER = ".\\\" Generated by tests/test_cli_man.py from the command's parser: do not edit.\n"

FILES = """.SH FILES
.I $GFAL_CONFIG_DIR/*.conf
(default
.IR /etc/gfal2.d/*.conf )
.RS
The gfal2 configuration files; \\fB\\-D\\fR overrides their settings.
.RE
"""

GFAL2_VERSION = """.TH GFAL2_VERSION 1 "" "gfal2 {version}" "xgfalclient"
.SH NAME
gfal2_version \\- Version tool for gfal2
.SH SYNOPSIS
.B gfal2_version
.SH DESCRIPTION
Prints the version of the gfal2 library whose behaviour xgfalclient reproduces, as
.BR GFAL\\-client\\-{version_roff} .
"""


def roff(text: str) -> str:
    """Plain text for a roff line: backslashes and hyphens escaped, no leading dot."""
    text = text.replace("\\", "\\e").replace("-", "\\-")
    return "\\&" + text if text.startswith((".", "'")) else text


def _metavar(action: argparse.Action) -> str:
    if action.choices is not None:
        return "{" + ",".join(str(choice) for choice in action.choices) + "}"
    return str(
        action.metavar or (action.dest if not action.option_strings else action.dest.upper())
    )


def _positional(action: argparse.Action) -> str:
    name = f"\\fI{roff(_metavar(action))}\\fR"
    return {"?": f"[{name}]", "*": f"[{name}]...", "+": f"{name} [{name}]..."}.get(
        str(action.nargs), name
    )


def _flags(action: argparse.Action) -> str:
    if not action.option_strings:
        return roff(_metavar(action))
    if action.nargs == 0:
        return roff(", ".join(action.option_strings))
    return roff(", ".join(f"{flag} {_metavar(action)}" for flag in action.option_strings))


def command_page(command: str) -> str:
    spec: base.Spec = importlib.import_module(f"xgfalclient.cli._{cli.COMMANDS[command]}").SPECS[
        command
    ]
    prog = f"gfal-{command}"
    parser = base.build_parser(prog, spec.name, spec.doc, spec.arguments)
    actions = parser._actions
    positionals = [action for action in actions if not action.option_strings]
    options = [action for action in actions if action.option_strings]
    summary = spec.doc.rstrip(".")
    lines = [
        HEADER,
        f'.TH {prog.upper()} 1 "" "gfal2-util {base.VERSION}" "xgfalclient"\n',
        ".SH NAME\n",
        f"{roff(prog)} \\- {roff(summary[:1].lower() + summary[1:])}\n",
        ".SH SYNOPSIS\n",
        f".B {roff(prog)}\n",
        "[\\fIOPTION\\fR]... " + " ".join(_positional(action) for action in positionals) + "\n",
        ".SH DESCRIPTION\n",
    ]
    if command == "legacy-bringonline":
        lines.append("Deprecated: prints a notice, then runs\n.BR gfal\\-bringonline (1).\n.PP\n")
    lines.append(roff(parser.description or "") + "\n")
    for title, group in (("ARGUMENTS", positionals), ("OPTIONS", options)):
        if group:
            lines.append(f".SH {title}\n")
        for action in group:
            lines.append(f".TP\n.B {_flags(action)}\n{roff(action.help or '')}\n")
    lines.append(FILES)
    others = sorted(f"gfal-{other}" for other in cli.COMMANDS if other != command)
    lines.append('.SH "SEE ALSO"\n')
    lines.append(",\n".join(f".BR {roff(other)} (1)" for other in others) + "\n")
    return "".join(lines)


def pages() -> dict[str, str]:
    from xgfalclient._version import GFAL2_VERSION as version

    found = {f"gfal-{command}.1": command_page(command) for command in cli.COMMANDS}
    found["gfal2_version.1"] = HEADER + GFAL2_VERSION.format(
        version=version, version_roff=roff(version)
    )
    return found


def test_man_pages_are_current() -> None:
    on_disk = {path.name: path.read_text() for path in MAN_DIR.glob("*.1")}
    assert on_disk == pages(), "regenerate with: python tests/test_cli_man.py"


def test_roff_escapes() -> None:
    assert roff(".x-y\\z") == "\\&.x\\-y\\ez"
    assert roff("'q") == "\\&'q"
    assert roff("plain") == "plain"


if __name__ == "__main__":
    MAN_DIR.mkdir(parents=True, exist_ok=True)
    for old in MAN_DIR.glob("*.1"):
        old.unlink()
    for name, text in pages().items():
        (MAN_DIR / name).write_text(text)
    sys.stdout.write(f"wrote {len(pages())} pages to {MAN_DIR}\n")
